spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:LoginPractice
    username: sa
    password:

session:
  store-type: jdbc
  jdbc:
    initialize-schema: always
